version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "gomod"
    schedule:
      interval: "weekly"
      timezone: "Asia/Shanghai"